// react/LoadView.jsx

import './style/LoadView.less'
class LoadView extends React.Component{




    render() {

        const { msg } = this.props;

        return <div className="loading-view">
            <div className="img">
                <div className="loader">
                    <div className="loader-inner line-scale-pulse-out-rapid">
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>

                    { msg && msg.length > 0 ? <p className="msg" >

                    </p> : []}

                </div>
            </div>
        </div>
    }
}

export default LoadView;

// vue/LoadView.vue
<template>
    <div class="loading-view">
        <div class="img">
            <div class="loader">
                <div class="loader-inner line-scale-pulse-out-rapid">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
                <p class="msg" v-if="msg && msg.length > 0">
                    {{msg}}
                </p>
            </div>
        </div>

    </div>
</template>

<script>


    import Vue from 'vue';

    import '../react/style/LoadView.less';


    export default {
        name: 'LoadView',


        data () {
            return {
            }
        },
        props: ['msg'],

    }
</script>
